name: My Workflow

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Detect something
        # Add your detection steps here
        run: echo "Detection step"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Job 2 step
        run: echo "This is Job 2"

  job3:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Job 3 step
        run: echo "This is Job 3"
